// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace TelecomML.Model
{
    public class ModelInput
    {
        [ColumnName("state"), LoadColumn(0)]
        public string State { get; set; }


        [ColumnName("account_length"), LoadColumn(1)]
        public float Account_length { get; set; }


        [ColumnName("area_code"), LoadColumn(2)]
        public float Area_code { get; set; }


        [ColumnName("international_plan"), LoadColumn(3)]
        public float International_plan { get; set; }


        [ColumnName("voice_mail_plan"), LoadColumn(4)]
        public float Voice_mail_plan { get; set; }


        [ColumnName("number_vmail_messages"), LoadColumn(5)]
        public float Number_vmail_messages { get; set; }


        [ColumnName("total_day_minutes"), LoadColumn(6)]
        public float Total_day_minutes { get; set; }


        [ColumnName("total_day_calls"), LoadColumn(7)]
        public float Total_day_calls { get; set; }


        [ColumnName("total_day_charge"), LoadColumn(8)]
        public float Total_day_charge { get; set; }


        [ColumnName("total_eve_minutes"), LoadColumn(9)]
        public float Total_eve_minutes { get; set; }


        [ColumnName("total_eve_calls"), LoadColumn(10)]
        public float Total_eve_calls { get; set; }


        [ColumnName("total_eve_charge"), LoadColumn(11)]
        public float Total_eve_charge { get; set; }


        [ColumnName("total_night_minutes"), LoadColumn(12)]
        public float Total_night_minutes { get; set; }


        [ColumnName("total_night_calls"), LoadColumn(13)]
        public float Total_night_calls { get; set; }


        [ColumnName("total_night_charge"), LoadColumn(14)]
        public float Total_night_charge { get; set; }


        [ColumnName("total_intl_minutes"), LoadColumn(15)]
        public float Total_intl_minutes { get; set; }


        [ColumnName("total_intl_calls"), LoadColumn(16)]
        public float Total_intl_calls { get; set; }


        [ColumnName("total_intl_charge"), LoadColumn(17)]
        public float Total_intl_charge { get; set; }


        [ColumnName("customer_service_calls"), LoadColumn(18)]
        public float Customer_service_calls { get; set; }


        [ColumnName("churn"), LoadColumn(19)]
        public string Churn { get; set; }


    }
}
